name: Feature Report
description: Request new Feature
title: "[FEATURE]: "
labels: ["기능"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        이번 이슈도 파이팅 화이팅 🔥
  - type: textarea
    id: newFeature
    attributes:
      label: 작업 사항 
      description: 어떤 기능을 추가할건가요? 
      placeholder: Splash API를 활용한 스플래쉬 화면 구현 
    validations:
      required: true
  - type: textarea
    id: featureTodo
    attributes:
      label: Todo
      description: 작업사항을 나누어 작성해주세요! 
      value: - [] todo1
    validations:
      required: false
