#!/bin/sh
echo "Running git pre-commit hook"

./gradlew ktlintCheck --daemon

# $? = ".gradlew ktlintFormat --daemon"에 대한 return 값
STATUS=$?

# 문제없이 끝났다면 exit 0, 아니면 1
# -ne: Not equals
[ $STATUS -ne 0 ] && exit 1
exit 0